Client/Models/ErrorViewModel.cs
using System;

namespace Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Client/Controllers/AccountsController.cs
using Client.Base;
using Client.Repositories.Data;
using HumanResourceAPI.Models;
using HumanResourceAPI.ModelView;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class AccountsController : BaseController<Account, AccountRepository, string>
    {
        private readonly AccountRepository accountRepository;

        public AccountsController(AccountRepository repository) : base(repository)
        {
            accountRepository = repository;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Login(Login login)
        {
            var result = accountRepository.Login(login);
            return Json(result);
        }

        [HttpPost("v1.0/login")]
        public async Task<IActionResult> Auth(Login login)
        {
            var jwtToken = await accountRepository.Auth(login);
            var token = jwtToken.idToken;

            string status = jwtToken.status.ToString();

            if (token == null)
            {
                TempData["status"] = status;
                TempData["message"] = jwtToken.message;
                return RedirectToAction("index","login");
            }

            HttpContext.Session.SetString("JWToken", token);
      
                return RedirectToAction("index", "home");
            
           
        }

  
        [HttpGet("Accounts/Logout")]
        public IActionResult Logout()
        {
          

            HttpContext.Session.Clear();

            return RedirectToAction("index", "login");
        }

    }
}

Client/Controllers/EmployeesController.cs
using Client.Base;
using Client.Repositories.Data;
using HumanResourceAPI.Models;
using HumanResourceAPI.ModelView;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles ="Direktur, Manager")]
    public class EmployeesController : BaseController<Employee, EmployeeRepository, string>
    {
        private readonly EmployeeRepository employeeRepository;
        public EmployeesController(EmployeeRepository repository) : base(repository)
        {
            employeeRepository = repository;
        }


        public IActionResult Master()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Chart()
        {
            return View();
        }

        [HttpDelete("Employees/Remove/{NIK}")]
        public JsonResult Remove(string NIK)
        {
            var result = employeeRepository.Remove(NIK);
            return Json(result);
        }

        [HttpGet("Employees/Detail/{NIK}")]
        public async Task<JsonResult> Detail(string NIK)
        {
            var result = await employeeRepository.Detail(NIK);
            return Json(result);
        }

        [HttpGet("Employees/Report")]
        public JsonResult ReportAll()
        {
            var result =  employeeRepository.ReportAll();
            return Json(result);
        }


        [HttpPost]
        public JsonResult Register(Register register)
        {
            var result = employeeRepository.Register(register);
            return Json(result);
        }


        [HttpPut]
        public JsonResult Update(Register register)
        {
            var result = employeeRepository.Update(register);
            return Json(result);
        }

        [HttpPost]
        public JsonResult Login(Register register)
        {
            var result = employeeRepository.Register(register);
            return Json(result);
        }


    }
}

Client/Controllers/ErrorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult NotFound()
        {
            return View();
        }

        public IActionResult Authorize()
        {
            return View();
        }

        public IActionResult Forbidden()
        {
            return View();
        }
    }
}

Client/Controllers/ExerciseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class ExerciseController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/HomeController.cs
using Client.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        [HttpGet("/Dashboard")]
        public IActionResult Index()
        {
            if (User.IsInRole("Employee"))
            {
                return RedirectToAction("index", "pokemon");
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Client/Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class LandingController : Controller
    {
        [HttpGet("v1.0/landing")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/LoginController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            var token = HttpContext.Session.GetString("JWToken");

            if (token == null)
            {
                return View();
            }

            return RedirectToAction("index", "home");

        }
    }
}

Client/Controllers/PokemonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    [Authorize(Roles = "Employee, Manager, Direktur")]
    public class PokemonController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/TestCorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class TestCorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Controllers/UniversitiesController.cs
using Client.Base;
using Client.Repositories.Data;
using HumanResourceAPI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{
    public class UniversitiesController : BaseController<University, UniversityRepository, string>
    {

        private readonly UniversityRepository universityRepository;
        public UniversitiesController(UniversityRepository repository) : base(repository)
        {
            universityRepository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Client/Views/Employees/Chart.cshtml
@{
    ViewData["Title"] = "Employee Chart Page";
    Layout = "_Layout";
}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Employee Chart</h1>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card h-100 shadow">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
            </div>
            <div class="card-body">
                <div id="employee-bar">

                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card h-100 shadow">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
            </div>
            <div class="card-body">
                <div id="employee-donut">

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/js/chart_employee.js"></script>
}

Client/Views/Exercise/Index.cshtml
@{
    ViewData["Title"] = "Exercise Page";
    Layout = "_Layout";
}
    <div class="row">
        <div class="col">
            <h2 class="title">The Basic Languange of the web : HTML</h2>
            <p class="date-post">Posted by <b>Mozilla</b> on Monday, June 21st 2027</p>
            <img id="image" src="/image/pic_html.jpeg" class="img-thumbnail mb-2" alt="HTML code on a screen" />
            <p class="body-topic">
                HTML (HyperText Markup Language) is the most basic building block of the Web.
                It defines the meaning and structure of web content.
                Other technologies besides HTML are generally used to describe a web page's appearance/presentation (CSS)
                or functionality/behavior (JavaScript).
            </p>
        </div>
    </div>
    <div class="button-group">
        <button onclick="htmlFunction()" id="button-html" class="btn btn-link">Html</button>
        <button onclick="cssFunction()" id="button-css" class="btn btn-link">Css</button>
        <button onclick="javascriptFunction()" id="button-javascript" class="btn btn-link">JavaScript</button>
    </div>

Client/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Dashboard Page";
    Layout = "_Layout";
}

<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
</div>

<div class="row">

    @*count employee*@
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            EMPLOYEES
                        </div>
                        <div id="count-employee" class="h5 mb-0 font-weight-bold text-gray-800">
                           
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-users fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*count account*@
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            ACCOUNTS
                        </div>
                        <div id="count-account" class="h5 mb-0 font-weight-bold text-gray-800">
                            
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-user-shield fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @*count education*@
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            EDUCATIONS
                        </div>
                        <div id="count-education" class="h5 mb-0 font-weight-bold text-gray-800">
                            
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-address-book fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>


    @*count university*@
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            UNIVERSITIES
                        </div>
                        <div id="count-university" class="h5 mb-0 font-weight-bold text-gray-800">
                            
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-university fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xl-6 col-lg-6">
        <div class="card h-100 shadow mb-4">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">University Sources</h6>
            </div>
            <div class="card-body">
                <div id="employee-bar">

                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-6 col-lg-6">
        <div class="card h-100 shadow">
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Gender Overview</h6>
            </div>
            <div class="card-body">
                <div id="employee-donut">

                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/js/chart_employee.js"></script>
}

Client/Views/Landing/Index.cshtml
@{
    ViewData["Title"] = "Landing Page";
    Layout = "_Layout_Landing";
}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="#">Employee Site</i></a>

    <!-- Links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="btn btn-sm btn-success" href="https://localhost:44300/login">LOGIN</a>
        </li>
    </ul>
</nav>

   <div class="container h-75">
       <div class="row h-100 justify-content-center align-items-center">
           <div class="col text-center">
               <h1 class="text-white">Welcome Employee</h1>
               <p class="text-light">This website is the result of the implementation of training in segment 3 frontend with the theme of managing workers.</p>
           </div>
       </div>
          
    </div>

   

Client/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login Page";
    Layout = "_Layout_Login";
}


<div class="row justify-content-center">
    <div class="col-md-10">
        @{
            var status = "";
            var message = "";

            if (TempData.ContainsKey("status"))
            {
                status = TempData["status"] as string;
                message = TempData["message"] as string;
            }

        }
    </div>
</div>

<div class="row justify-content-center d-flex align-items-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-6 d-none d-lg-block bg-login-image">

                    </div>
                    <div class="col-lg-6">
                        @{
                            if (status == "BadRequest")
                            {
                                <div class="alert alert-danger alert-dismissible fade show mx-2 my-2">
                                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                                    @message
                                </div>
                            }
                        }
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                            </div>
                            <form class="user" method="post" action="/v1.0/Login" id="asd">
                                <div class="form-group">
                                    <input type="email" name="Email" class="form-control form-control-user"
                                           id="exampleInputEmail" aria-describedby="emailHelp"
                                           placeholder="Enter Email Address..." required>
                                </div>
                                <div class="form-group">
                                    <input type="password" name="Password" class="form-control form-control-user"
                                           id="exampleInputPassword" placeholder="Password" required>
                                </div>
                                <div class="form-group">
                                    <div class="custom-control custom-checkbox small">
                                        <input type="checkbox" class="custom-control-input" id="customCheck">
                                        <label class="custom-control-label" for="customCheck">
                                            Remember
                                            Me
                                        </label>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary btn-user btn-block">
                                    Login
                                </button>

                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="#">Forgot Password?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>

    @*bootstrap source*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    @*datatables source*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.1.0/css/buttons.dataTables.min.css" />

    @*font awesemo*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    @*css native*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/template/css/sb-admin-2.css" rel="stylesheet">

    @*sweet alert*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">


</head>
<body id="page-top">

    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-briefcase"></i>
                </div>
                <div class="sidebar-brand-text mx-3">HR ADMIN</div>
            </a>
            @if (User.IsInRole("Manager") || User.IsInRole("Direktur"))
            {
                <!-- Divider -->
                <hr class="sidebar-divider my-0">

                <!-- Nav Item - Dashboard -->
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-fw fa-tachometer-alt"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider">

                <!-- Nav Item - Employee -->

                <li class="nav-item">
                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                       aria-expanded="true" aria-controls="collapseTwo">
                        <i class="fas fa-users"></i>
                        <span>Employee</span>
                    </a>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                        <div class="bg-white py-2 collapse-inner rounded">
                            <a class="collapse-item" asp-controller="Employees" asp-action="Master">Master</a>
                        </div>
                    </div>
                </li>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">
            }

            <!-- Nav Item - Pokemon -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Pokemon" asp-action="Index">
                    <i class="fas fa-dove"></i>
                    <span>Pokemon</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Exercise -->
            <li class="nav-item">
                <a class="nav-link" asp-controller="Exercise" asp-action="Index">
                    <i class="fas fa-book-open"></i>
                    <span>Exercise</span>
                </a>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>



        </ul>

        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>



                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">User</span>
                                <img class="img-profile rounded-circle"
                                     src="~/lib/template/img/undraw_profile.svg">

                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="Accounts/Logout">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
        </div>

    </div>

    @*jquery source*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    @*bootstrap source*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @*datatables source*@
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.1.0/js/dataTables.buttons.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.1.0/js/buttons.colVis.min.js"></script>

    @*sweet alert source*@
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    @*apex chart source*@
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

    @*javascript native*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/template/js/sb-admin-2.min.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_Layout_Landing.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>

    @*font nunito*@
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    @*font awesemo*@
    <link href="~/lib/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    @*sweet alert*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">

    @*bootstrap*@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">

    @*css native*@
    <link href="~/lib/template/css/sb-admin-2.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />

    <style>
        body, html {
            height: 100%;
        }
        .bg-body {
            background-image: url("/image/mario-gogh-VBLHICVh-lI-unsplash.jpg");
            height: 100%;
            background-position: center;
            background-repeat: no-repeat;
            background-size: cover;
        }
      
    </style>
</head>
<body class="bg-body">

    @RenderBody()

    @*jquery source*@
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>


    @*bootstrap source*@
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_Layout_Login.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client</title>

    @*font awesemo*@
    <link href="~/lib/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">

    @*sweet alert*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.2.0/sweetalert2.min.css">

    @*css native*@
    <link href="~/lib/template/css/sb-admin-2.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />



</head>
<body class="bg-light">
    <div class="container">
        @RenderBody()
    </div>

    @*jquery source*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>

    @*bootstrap source*@
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>


    @*sweet alert source*@
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.5/dist/sweetalert2.all.min.js"></script>


    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Client/Views/Shared/_Layout_Native.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Latihan</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @RenderBody()
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>